Controllers/CabinetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ApplicationDbContex.Data;
using BW5.Models;

namespace BW5.Controllers
{
    public class CabinetsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CabinetsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Cabinets
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cabinets.ToListAsync());
        }

        // GET: Cabinets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cabinet = await _context.Cabinets
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cabinet == null)
            {
                return NotFound();
            }

            return View(cabinet);
        }

        // GET: Cabinets/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cabinets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Code")] Cabinet cabinet)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cabinet);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cabinet);
        }

        // GET: Cabinets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cabinet = await _context.Cabinets.FindAsync(id);
            if (cabinet == null)
            {
                return NotFound();
            }
            return View(cabinet);
        }

        // POST: Cabinets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Code")] Cabinet cabinet)
        {
            if (id != cabinet.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cabinet);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CabinetExists(cabinet.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cabinet);
        }

        // GET: Cabinets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cabinet = await _context.Cabinets
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cabinet == null)
            {
                return NotFound();
            }

            return View(cabinet);
        }

        // POST: Cabinets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cabinet = await _context.Cabinets.FindAsync(id);
            if (cabinet != null)
            {
                _context.Cabinets.Remove(cabinet);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CabinetExists(int id)
        {
            return _context.Cabinets.Any(e => e.Id == id);
        }
    }
}

Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ApplicationDbContex.Data;
using BW5.Models;

namespace BW5.Controllers
{
    public class SalesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SalesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Sales
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Sales.Include(s => s.Product);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Sales/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sales = await _context.Sales
                .Include(s => s.Product)
                .ThenInclude(p => p.Supplier)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sales == null)
            {
                return NotFound();
            }

            return View(sales);
        }

        // GET: Sales/Create
        public IActionResult Create()
        {
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Name");
            return View();
        }

        // POST: Sales/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CustomerFiscalCode,ProductId,PrescriptionNumber,SaleDate")] Sales sales)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sales);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Name", sales.ProductId);
            return View(sales);
        }

        // GET: Sales/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sale = await _context.Sales
                .Include(s => s.Product)
                    .ThenInclude(p => p.Drawer)
                        .ThenInclude(d => d.Cabinet)
                .FirstOrDefaultAsync(s => s.Id == id);

            if (sale == null)
            {
                return NotFound();
            }

            var selectedCabinetId = sale.Product?.Drawer?.CabinetId;
            var selectedDrawerId = sale.Product?.DrawerId;

            var cabinets = await _context.Cabinets.ToListAsync();
            var drawers = selectedCabinetId.HasValue
                ? await _context.Drawers.Where(d => d.CabinetId == selectedCabinetId.Value).ToListAsync()
                : new List<Drawer>();
            var products = selectedDrawerId.HasValue
                ? await _context.Products.Where(p => p.DrawerId == selectedDrawerId.Value).ToListAsync()
                : new List<Product>();

            ViewBag.Cabinets = cabinets;
            ViewBag.Drawers = drawers;
            ViewBag.Products = products;

            return View(sale);
        }

        // POST: Sales/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CustomerFiscalCode,ProductId,PrescriptionNumber,SaleDate")] Sales sale)
        {
            if (id != sale.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sale);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SalesExists(sale.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            var selectedProduct = await _context.Products
                .Include(p => p.Drawer)
                    .ThenInclude(d => d.Cabinet)
                .FirstOrDefaultAsync(p => p.Id == sale.ProductId);

            var selectedCabinetId = selectedProduct?.Drawer?.CabinetId;
            var selectedDrawerId = selectedProduct?.DrawerId;

            var cabinets = await _context.Cabinets.ToListAsync();
            var drawers = selectedCabinetId.HasValue
                ? await _context.Drawers.Where(d => d.CabinetId == selectedCabinetId.Value).ToListAsync()
                : new List<Drawer>();
            var products = selectedDrawerId.HasValue
                ? await _context.Products.Where(p => p.DrawerId == selectedDrawerId.Value).ToListAsync()
                : new List<Product>();

            ViewBag.Cabinets = cabinets;
            ViewBag.Drawers = drawers;
            ViewBag.Products = products;

            return View(sale);
        }

        // GET: Sales/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sales = await _context.Sales
                .Include(s => s.Product)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sales == null)
            {
                return NotFound();
            }

            return View(sales);
        }

        // POST: Sales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sales = await _context.Sales.FindAsync(id);
            if (sales != null)
            {
                _context.Sales.Remove(sales);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SalesExists(int id)
        {
            return _context.Sales.Any(e => e.Id == id);
        }

        // GET: Sales/CustomReport
        public async Task<IActionResult> CustomReport()
        {
            // Logica per generare il report personalizzato
            var reportData = await _context.Sales
                .Include(s => s.Product)
                .ThenInclude(p => p.Supplier)
                .ToListAsync();

            return View(reportData);
        }

        // GET: Sales/DrawerAndCabinetPartial
        public async Task<IActionResult> DrawerAndCabinetPartial()
        {
            // Logica per ottenere i dati di Drawer e Cabinet
            var drawerAndCabinetData = await _context.Drawers
                .Include(d => d.Cabinet)
                .ToListAsync();

            return PartialView("_DrawerAndCabinetPartial", drawerAndCabinetData);
        }

        // GET: Sales/GetSalesByDate
        public async Task<IActionResult> GetSalesByDate(DateTime date)
        {
            var sales = await _context.Sales
                .Include(s => s.Product)
                .Where(s => s.SaleDate.Date == date.Date)
                .ToListAsync();

            return PartialView("_SalesByDatePartial", sales);
        }

        // GET: Sales/GetSalesByCustomer
        public async Task<IActionResult> GetSalesByCustomer(string fiscalCode)
        {
            var sales = await _context.Sales
                .Include(s => s.Product)
                .Where(s => s.CustomerFiscalCode == fiscalCode)
                .ToListAsync();

            return PartialView("_SalesByCustomerPartial", sales);
        }
    }
}

Controllers/VisitsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BW5.Models;
using ApplicationDbContex.Data;

namespace BW5.Controllers
{
    public class VisitsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VisitsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Visits
        public async Task<IActionResult> Index()
        {
            var visits = _context.Visits.Include(v => v.Animal);
            return View(await visits.ToListAsync());
        }

        // GET: Visits/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visit = await _context.Visits
                .Include(v => v.Animal)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (visit == null)
            {
                return NotFound();
            }

            return View(visit);
        }

        // GET: Visits/Create
        public IActionResult Create()
        {
            ViewBag.AnimalId = new SelectList(_context.Animals.Select(a => new
            {
                Id = a.Id,
                Description = a.Name + " - " + a.OwnerFirstName + " " + a.OwnerLastName
            }), "Id", "Description");
            return View();
        }

        // POST: Visits/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,VisitDate,ObjectiveExam,PrescribedTreatment,AnimalId")] Visit visit)
        {
            if (ModelState.IsValid)
            {
                _context.Add(visit);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.AnimalId = new SelectList(_context.Animals.Select(a => new
            {
                Id = a.Id,
                Description = a.Name + " - " + a.OwnerFirstName + " " + a.OwnerLastName
            }), "Id", "Description", visit.AnimalId);
            return View(visit);
        }

        // GET: Visits/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visit = await _context.Visits.FindAsync(id);
            if (visit == null)
            {
                return NotFound();
            }
            ViewBag.AnimalId = new SelectList(_context.Animals.Select(a => new
            {
                Id = a.Id,
                Description = a.Name + " - " + a.OwnerFirstName + " " + a.OwnerLastName
            }), "Id", "Description", visit.AnimalId);
            return View(visit);
        }

        // POST: Visits/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,VisitDate,ObjectiveExam,PrescribedTreatment,AnimalId")] Visit visit)
        {
            if (id != visit.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(visit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VisitExists(visit.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.AnimalId = new SelectList(_context.Animals.Select(a => new
            {
                Id = a.Id,
                Description = a.Name + " - " + a.OwnerFirstName + " " + a.OwnerLastName
            }), "Id", "Description", visit.AnimalId);
            return View(visit);
        }

        // GET: Visits/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var visit = await _context.Visits
                .Include(v => v.Animal)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (visit == null)
            {
                return NotFound();
            }

            return View(visit);
        }

        // POST: Visits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var visit = await _context.Visits.FindAsync(id);
            if (visit != null)
            {
                _context.Visits.Remove(visit);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VisitExists(int id)
        {
            return _context.Visits.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BW5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BW5.styles.css" asp-append-version="true" />
    <style>
    .sidebar {
    height: 100%;
    width: 200px;
    position: fixed;
    top: 0;
    left: 0;
    background-color: #343a40;
    padding-top: 20px;
    }

    .sidebar .logo {
    text-align: center;
    margin-bottom: 20px;
    }

    .sidebar .logo img {
    max-width: 120px;
    height: auto;
    border-radius: 15%;
    }

    .sidebar a {
    padding: 10px 15px;
    text-decoration: none;
    font-size: 18px;
    color: #61dafb;
    display: block;
    }

    .sidebar a:hover {
    background-color: #ddd;
    }

    .content {
    margin-left: 260px;
    padding: 20px;
    background-color: #f8f9fa;
    color: #343a40;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    min-height: calc(100vh - 80px); /* Assicura che il contenuto riempia lo spazio sopra il footer */
    }

    footer {
    background-color: #343a40;
    color: #adb5bd;
    padding: 10px 0; /* Riduce l'altezza del footer */
    text-align: center;
    position: fixed;
    bottom: 0;
    width: 100%;
    height: auto; /* Permette al contenuto del footer di determinare l'altezza */
    }

    footer h5 {
    color: #61dafb;
    margin-bottom: 10px; /* Riduce lo spazio sotto il titolo */
    }

    footer a {
    color: #61dafb;
    text-decoration: none;
    }

    footer a:hover {
    text-decoration: underline;
    }
    </style>
</head>
<body>
    <div class="sidebar">
        <!-- Spazio per il logo -->
        <div class="logo">
            <img src="~/images/logo_nosfondo.png" alt="Logo">
        </div>

        <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        <!--Farmacista-->
        <a asp-area="" asp-controller="Animals" asp-action="Index">Gestione Animali</a>
        <a asp-area="" asp-controller="Recoveries" asp-action="Index">Gestione Ricoveri</a> 
        <a asp-area="" asp-controller="Visits" asp-action="Index">Gestione Visite</a>

        <!--Veterinario-->
        <a asp-area="" asp-controller="Cabinets" asp-action="Index">Gestione Armadi</a>
        <a asp-area="" asp-controller="Drawers" asp-action="Index">Gestione Cassetti</a>
        <a asp-area="" asp-controller="Products" asp-action="Index">Gestione Prodotti</a>
        <a asp-area="" asp-controller="Sales" asp-action="Index">Gestione Vendite</a>
        <a asp-area="" asp-controller="Suppliers" asp-action="Index">Gestione Fornitori</a>
        <!-- Aggiungi altri link qui secondo le tue necessità -->
    </div>
    <div class="content">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

@*     <footer class="border-top footer  mt-5">
        <div class="container">
            <div class="row">
                <!-- Sezione Contatti -->
                <div class="col-md-4">
                    <h5>Contatti</h5>
                    <p>
                        <strong>Indirizzo:</strong><br>
                        Via degli Animali, 123<br>
                        00100 Roma, Italia
                    </p>
                    <p>
                        <strong>Telefono:</strong><br>
                        +39 06 1234 5678
                    </p>
                    <p>
                        <strong>Email:</strong><br>
                        <a href="mailto:info@clinicaveterinaria.it">info@clinicaveterinaria.it</a>
                    </p>
                </div>
                <!-- Sezione Orari di Apertura -->
                <div class="col-md-4">
                    <h5>Orari di Apertura</h5>
                    <p>
                        <strong>Lunedì - Venerdì:</strong><br>
                        09:00 - 18:00
                    </p>
                    <p>
                        <strong>Sabato:</strong><br>
                        09:00 - 13:00
                    </p>
                    <p>
                        <strong>Domenica:</strong><br>
                        Chiuso
                    </p>
                </div>
                <!-- Sezione Social Media -->
                <div class="col-md-4">
                    <h5>Seguici sui Social</h5>
                    <a href="https://www.facebook.com/clinicaveterinaria" target="_blank">Facebook</a><br>
                    <a href="https://www.instagram.com/clinicaveterinaria" target="_blank">Instagram</a><br>
                    <a href="https://www.twitter.com/clinicaveterinaria" target="_blank">Twitter</a>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-12 text-center">
                    &copy; 2024 - clinica - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </div>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>